# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cobracli < Formula
  desc ""
  homepage "https://github.com/bishal7679/Cobra-CLI/"
  version "0.2.1-next"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bishal7679/Cobra-CLI/releases/download/v0.2.0/cobra-cli_0.2.0_darwin_arm64.zip"
      sha256 "98fae2150f06599c0f1b8c89ed1497ba0e1b7af0e2912a047b81419843e6b2ae"

      def install
        bin.install "cobracli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bishal7679/Cobra-CLI/releases/download/v0.2.0/cobra-cli_0.2.0_darwin_amd64.zip"
      sha256 "db8142191c4391e150179ac717274b8e61284d772e3a5860464ad5e2d32ba1b5"

      def install
        bin.install "cobracli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bishal7679/Cobra-CLI/releases/download/v0.2.0/cobra-cli_0.2.0_linux_arm64.zip"
      sha256 "0d23874691b25c57fbf24a0584a05dbd11028270ef20e6086ebc8af555e7d75a"

      def install
        bin.install "cobracli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bishal7679/Cobra-CLI/releases/download/v0.2.0/cobra-cli_0.2.0_linux_amd64.zip"
      sha256 "e7b9a622b922c4ec0c4eeffbcaf3a90937c71d317587b5be92e1c1728a7ea5f1"

      def install
        bin.install "cobracli"
      end
    end
  end
end
