# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cobracli < Formula
  desc ""
  homepage "https://github.com/bishal7679/Cobra-CLI/"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bishal7679/Cobra-CLI/releases/download/v0.2.0/cobra-cli_0.2.0_darwin_arm64.zip"
      sha256 "fbdd47a8f1e81f5b246451ea3481ae26fc5e77bce2c59fdb8427c1e75255bf53"

      def install
        bin.install "cobracli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bishal7679/Cobra-CLI/releases/download/v0.2.0/cobra-cli_0.2.0_darwin_amd64.zip"
      sha256 "d11e85bd1a202e629d0ca0b0256f63bec491a20113fd7ebd0c7c2a19006de51d"

      def install
        bin.install "cobracli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bishal7679/Cobra-CLI/releases/download/v0.2.0/cobra-cli_0.2.0_linux_arm64.zip"
      sha256 "6e9c7802a548b175610d0f5b998105ef60735eb8f62e2702d49eb80d3ad9ac10"

      def install
        bin.install "cobracli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bishal7679/Cobra-CLI/releases/download/v0.2.0/cobra-cli_0.2.0_linux_amd64.zip"
      sha256 "a99b449475b580c47c7ad12d1b6b5bf706506566452298db7fa7ea21b46971a2"

      def install
        bin.install "cobracli"
      end
    end
  end
end
